### PR TITLE
initial audio

### PR DESCRIPTION
**Pull request by christianholman**
Initial draft for audio playing audio. State holds an array of audio files per action so that we can arbitrarily pick between them like playing multiple keystroke sounds in the future.

Adds:
playAudio function in config/state.ts
menu bar item to toggle mute
various sounds

### CODE REVIEW

**Comment by christianholman** [comment]
need to fix up a bunch of linter errors / clientside .window stuff, will pick up

**Comment by r3oath** [comment]
I hoped to catch you before you went too far with this, but you were too quick 😂

I was thinking about this over the weekend, and it would be silly for us to miss this opportunity to lay the foundations for other event-based functionality in the app. I've just pushed a few changes to the develop branch that introduces `lastEvent` and `lastEventTime` to the state object. The supported event types at the moment are `failureSlow`, `failureTypo`, `gameComplete`, `streakComplete`, `type`, and `wordComplete`.

Given the update, it'd be much cleaner and more scalable for you to move the audio FX-related logic into a custom hook under `/hooks`, perhaps calling it `useAudioEffects` and calling it from `/app/page.tsx`. Here you can use `useEffect` to register and unregister the audio API in a more idiomatic React manner and use `state.lastEventTime` as a watched dependency. Every time `state.lastEventTime` changes, you can switch over `state.lastEvent` to dispatch the appropriate sound effect for the event type.

**Comment by christianholman** [comment]
> I hoped to catch you before you went too far with this, but you were too quick 😂
> 
> 
> 
> I was thinking about this over the weekend, and it would be silly for us to miss this opportunity to lay the foundations for other event-based functionality in the app (e.g., popping confetti when you complete a streak). 
> 
> 
> 
> I've just pushed a few changes to the develop branch that introduces `lastEvent` and `lastEventTime` to the state object. The supported event types at the moment are `failureSlow`, `failureTypo`, `gameComplete`, `streakComplete`, `type`, and `wordComplete`.
> 
> 
> 
> Given the update, it'd be much cleaner and more scalable for you to move the audio FX-related logic into a custom hook under `/hooks`, perhaps calling it `useAudioEffects` and calling it from `/app/page.tsx`. Here you can use `useEffect` to register and unregister the audio API in a more idiomatic React manner and use `state.lastEventTime` as a dependency. Every time `state.lastEventTime` changes, you can switch over `state.lastEvent` to dispatch the appropriate sound effect for the event type.

Awesome, will reimplement with the hooks method, was thinking that as I was writing in the state file lol, not too big of a system so shouldn't be too bad of a transfer

**Comment by r3oath** [comment]
> Awesome, will reimplement with the hooks method, was thinking that as I was writing in the state file lol, not too big of a system so shouldn't be too bad of a transfer

Yeah, that state file/reducer is already quite complicated, so I'd like to keep it as clean as possible :)

As a reference, check out PR #42 — I'm making use of the new event system there for confetti after a successful streak or game completion.

**Comment by r3oath** [comment]
Just a heads-up, I'm going to add a dedicated SFX menu, which we can house the settings for features like confetti, audio, animation, etc. I'll add it in as part of #42. So hold off creating any menu options until that's ready. But feel free to get the core of the audio engine in place and firing from the state events in the meantime.

**Comment by christianholman** [comment]
> 

will get started on this in the next couple of days, will work off your PR

**Comment by r3oath** [comment]
I've merged that PR into the `develop` branch now.

**Comment by christianholman** [comment]
followed up in #44

**Pull request closed without merging**
